#!/usr/bin/env bash

set -eu

EULA="${EULA:-false}"
if [ "${EULA}" != "true" ]; then
    echo >&2 "Please accept the Minecraft EULA at"
    echo >&2 "  https://account.mojang.com/documents/minecraft_eula"
    echo >&2 "by marking the EULA as accepted in docker-compose.yml"
    echo >&2 "  EULA=true"
    exit 1
fi

echo "# Generated by docker
# on $(date)
eula=${EULA}" > /data/eula.txt

set +x
java "-Xmx${MEMORY}" -jar "/minecraft/minecraft_server.jar"
